#!/bin/sh
rm -f "/tmp/$2.dir" "/tmp/$2.pag"
awk '{
        printf "%s\t", $0
        for (i = 0; i < 40; i++)
                printf "%s.", $0
        printf "\n"
}' < /usr/share/dict/words | $1 build "/tmp/$2"
